config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 前台
  root "home#index"
  ## 搜尋
  post :search, to: "home#search"
  get :search_result, to: "home#search_result"
  ## 飯店專區
  resources :hotels, only: [:index] do
    resources :rooms do
      member do
        get :reservation
        post :booking
      end
    end
  end
  ## 會員專區
  resources :user do
    resources :booking_record do
      post :cancel, on: :member
    end
  end

  # 後台
  namespace :admin do
    root "home#index"
    resources :users_management do
      post :deposit, on: :member
    end
    resources :hotels do
      resources :rooms
    end
    resources :booking_records
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BackController
  def index
    
  end
end

app/controllers/home_controller.rb
class HomeController < FrontController
  def index
    @search = Search.new
    @search_result ||= [] 
  end

  def search
    @search = Search.new(search_params)
    @search_result = @search.perform(search_params)
    redirect_to search_result_path(rooms: @search_result)
  end

  def search_result
    @rooms = Room.includes(:room_type, :hotel).find(params[:rooms])
  end

  private

  def search_params
    params.require(:search).permit(:begin_date, :end_date, :person_count, :room_type)
  end
end

app/views/home/index.html.erb
<h2>前台首頁</h2>

<% if user_signed_in? %>
  <p><%= link_to '會員專區', user_index_path %></p>
<% end %>
<p><%= link_to '預約飯店', hotels_path %></p>

<h2>搜尋房間</h2>
<%= form_for @search, url: '/search' do |f| %>
  <%= f.label :begin_date, '住宿日' %>
  <%= f.date_field :begin_date %>
  ~
  <%= f.date_field :end_date %>
  <%= f.label :person_count, '入住人數' %>
  <%= f.number_field :person_count, value: 1 %>
  <%= f.select :room_type, options_for_select(RoomType.room_types.map{ |key, value| [RoomType.room_types[key], RoomType.room_types.key(value)]}, RoomType.room_types) %>
  <%= f.submit '搜尋', disable_with: '搜尋中...' %>
  <!-- form_for @object, html: { multipart: true }, do |f| -->
  <!-- form_for @object, html: { class: "classname" }, do |f| -->
<% end %>

app/views/home/search_result.html.erb
<h2>搜尋結果</h2>
<% @rooms.each do |room| %>
  <div>
    <p>飯店: <%= room.hotel.name %></p>
    <p>房號: <%= room.room_number %></p>
    <p>房間類型: <%= room.room_type.room_type_zh %></p>
    <p>價格: <%= room.price %></p>
  </div>
<% end %>