config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 前台
  root "home#index"
  ## 搜尋
  post :search, to: "home#search"
  get :search_result, to: "home#search_result"
  ## 飯店專區
  resources :hotels, only: [:index] do
    resources :rooms do
      member do
        get :reservation
        post :booking
      end
    end
  end
  ## 會員專區
  resources :user do
    resources :booking_record do
      post :cancel, on: :member
    end
  end

  # 後台
  namespace :admin do
    root "home#index"
    resources :users_management do
      post :deposit, on: :member
    end
    resources :hotels do
      resources :rooms
    end
    resources :booking_records
  end
end

app/models/hotel.rb
# == Schema Information
#
# Table name: hotels
#
#  id            :integer          not null, primary key
#  code          :string
#  description   :string
#  name          :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  hotel_type_id :integer          not null
#
# Indexes
#
#  index_hotels_on_hotel_type_id  (hotel_type_id)
#
# Foreign Keys
#
#  hotel_type_id  (hotel_type_id => hotel_types.id)
#
class Hotel < ApplicationRecord
  has_many :rooms
  belongs_to :hotel_type

  def enable_count
    rooms.count
  end

  def total_count
    rooms.count
  end
end

app/models/hotel_type.rb
# == Schema Information
#
# Table name: hotel_types
#
#  id         :integer          not null, primary key
#  type_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class HotelType < ApplicationRecord
  has_many :hotels

  enum hotel_types: {
    hotel: '一般旅館',
    hostel: '青年旅館',
    guest_house: '民宿',
    inn: '酒館',
    motel: '汽車旅館',
    rental: '公寓',
    resort: '渡假村',
    ryokan: '日式旅館'
  }

  def hotel_type_zh
    HotelType.hotel_types[self.type_name]
  end
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < Admin::BackController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.includes(:hotel_type).all
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :hotel_type, :code, :total_count, :description)
    end
end

app/controllers/hotels_controller.rb
class HotelsController < FrontController
  def index
    @hotels = Hotel.includes(:hotel_type)
    @search = Search.new
  end

  def search
    search = Search.new(search_params)
    @search_result = search.perform
    render json: @search_result
  end

  private

  def search_params
    params.require(:search).permit(:begin_date, :end_date, :person_count, :room_type)
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/admin/hotels/_form.html.erb
<%= form_with(model: [:admin ,hotel], local: true) do |form| %>
  <% if hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hotel_type %>
    <%= form.select :hotel_type, options_for_select(HotelType.hotel_types.map{ |key, value| [key.titleize, HotelType.hotel_types.key(value)]}, HotelType.hotel_types) %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit '更新'  %>
  </div>
<% end %>

app/views/admin/hotels/edit.html.erb
<h1>編輯飯店</h1>

<%= render 'form', hotel: @hotel %>

<p><%= link_to '建立房間', new_admin_hotel_room_path(@hotel) %></p>
<p><%= link_to '回飯店清單', admin_hotels_path %></p>

app/views/admin/hotels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>飯店清單</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>名稱</th>
      <th>類型</th>
      <th>代號</th>
      <th>空房數</th>
      <th>說明</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.id %></td>
        <td><%= hotel.name %></td>
        <td><%= hotel.hotel_type.hotel_type_zh %></td>
        <td><%= hotel.code %></td>
        <td><%= hotel.enable_count %>/<%= hotel.total_count %></td>
        <td><%= hotel.description %></td>
        <td><%= link_to '詳細', admin_hotel_path(hotel) %></td>
        <td><%= link_to '編輯', edit_admin_hotel_path(hotel) %></td>
        <td><%= link_to '刪除', admin_hotel_path(hotel), method: :delete, data: { confirm: '確定刪除飯店?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '建立新飯店', new_admin_hotel_path %>

app/views/admin/hotels/new.html.erb
<h1>建立新飯店</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to '回飯店清單', admin_hotels_path %>

app/views/admin/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名稱:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>類型:</strong>
  <%= @hotel.hotel_type.hotel_type_zh %>
</p>

<p>
  <strong>代碼:</strong>
  <%= @hotel.code %>
</p>

<p>
  <strong>現有房間:</strong>
  <ul>
    <% @hotel.rooms.map do |room| %>
      <li>
        <span><%= link_to room.room_number, admin_hotel_room_path(@hotel, room) %></span>
        <span style="margin-left: 10px;"><%= room.booking_records[0].booking_record_datetime if room.booking_records.count > 0 %></span>
      </li>
    <% end %>
  </ul>
</p>

<p>
  <strong>最大房間:</strong>
  <%= @hotel.total_count %>
</p>

<p>
  <strong>說明:</strong>
  <%= @hotel.description %>
</p>

<%= link_to '編輯', edit_admin_hotel_path(@hotel) %> |
<%= link_to '返回', admin_hotels_path %>