config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 前台
  root "home#index"
  ## 搜尋
  post :search, to: "home#search"
  get :search_result, to: "home#search_result"
  ## 飯店專區
  resources :hotels, only: [:index] do
    resources :rooms do
      member do
        get :reservation
        post :booking
      end
    end
  end
  ## 會員專區
  resources :user do
    resources :booking_record do
      post :cancel, on: :member
    end
  end

  # 後台
  namespace :admin do
    root "home#index"
    resources :users_management do
      post :deposit, on: :member
    end
    resources :hotels do
      resources :rooms
    end
    resources :booking_records
  end
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id           :integer          not null, primary key
#  person_count :integer
#  price        :integer
#  room_number  :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  hotel_id     :integer          not null
#  room_type_id :integer          not null
#
# Indexes
#
#  index_rooms_on_hotel_id      (hotel_id)
#  index_rooms_on_room_type_id  (room_type_id)
#
# Foreign Keys
#
#  hotel_id      (hotel_id => hotels.id)
#  room_type_id  (room_type_id => room_types.id)
#
class Room < ApplicationRecord
  belongs_to :hotel
  belongs_to :room_type
  has_many :booking_records

  # 符合房間類型的房間
  scope :room_type_for, -> (query) { joins(:room_type).where("room_types.type_name = ?", query).references(:room_type) }

  # 有預約記錄的房間
  scope :have_booking_records, -> { includes(:booking_records).where("booking_records.room_id IS NOT NULL").references(:booking_records) }

  # 有效預約單
  scope :valid_booking_records, -> { joins(:booking_records).where("booking_records.status <= 1").references(:booking_records) }

  # 該日期已有 on單預約記錄的房間
  scope :includes_date_record_rooms, -> (begin_date, end_date) {
    includes(:booking_records)
    .where("booking_records.status <= 1")
    .where("
      (booking_records.begin_date < ? AND booking_records.end_date > ?) OR
      (booking_records.begin_date > ? AND booking_records.end_date < ?) OR
      (booking_records.begin_date < ? AND booking_records.end_date > ?) OR
      (booking_records.begin_date < ? AND booking_records.end_date > ?)", 
      begin_date, begin_date, begin_date, end_date, end_date, begin_date, begin_date, end_date)
    .references(:booking_records)
  }

  def room_is_enough? person_count
    self.person_count >= person_count
  end

  def reservation_number
    false # 待改
  end

  # 確認該房間日期是否留空
  def check_date_is_enable date
    self.booking_records.valid.includes_date_record_count(date) == 0
  end

  def is_enable_to_booking_rooms date
    Room.all.excluding(Room.have_booking_records) << Room.have_booking_records.excluding(Room.includes_date_record_rooms(Time.now - 1.days, Time.now - 3.days))
  end
end

app/models/room_type.rb
# == Schema Information
#
# Table name: room_types
#
#  id                   :integer          not null, primary key
#  person_default_count :integer
#  type_name            :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
class RoomType < ApplicationRecord
  has_many :rooms

  enum room_types: {
    single: '單人房',
    double: '單床雙人房',
    twin: '雙床雙人房',
    triple: '三人房'
  }

  def room_type_zh
    RoomType.room_types[self.type_name]
  end
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < Admin::BackController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    print("我是參數", params[:hotel_id])
    @room = Room.find(params[:id])
    @hotel = params[:hotel_id]
  end

  # GET /rooms/new
  def new
    @room = Room.new(hotel_id: params[:hotel_id])
    @hotel = Hotel.find(params[:hotel_id])
  end

  # GET /rooms/1/edit
  def edit
    print("我是參數", params[:hotel_id])
    @hotel = Hotel.find(params[:hotel_id])
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to admin_hotel_path(params[:hotel_id]), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to admin_hotel_path(params[:hotel_id]), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to admin_hotel_path(params[:hotel_id]), notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def reservation
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:room_number, :room_type, :price, :hotel_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < FrontController
  before_action :authenticate_user!, only: [:reservation, :booking]

  def index
    @hotel = Hotel.find(params[:hotel_id])
    @room_type_ids = @hotel.rooms.joins(:room_type).distinct.pluck(:room_type_id)
    @roomtyps = RoomType.find(@room_type_ids)
  end

  def reservation
    @hotel = Hotel.find(params[:hotel_id])
    @room = Room.find(params[:id])
  end

  def booking
    room = Room.find(params[:id])
    begin_datetime = params[:begin_datetime]
    end_datetime = params[:end_datetime]
    person_count = to_int_if_not(params[:person_count])
    # 檢查有無 有效預約記錄
    unless is_vacancy?(room, begin_datetime, end_datetime)
      redirect_back fallback_location: root_path, alert: '已經被預約了'
      return
    end

    # 檢查房間是否足夠
    unless room.room_is_enough?(person_count)
      redirect_back fallback_location: root_path, alert: '人數超過限制'
      return
    end

    # 檢查錢是否足夠
    unless current_user.amount_has_enough?(room.price)
      redirect_back fallback_location: root_path, alert: '款項不夠'
      return
    end

    current_user.booking_and_pay(room, begin_datetime, end_datetime, person_count)
    redirect_to hotel_rooms_path(params[:hotel_id])
  end

  private

  # 待改範圍、方法
  def is_vacancy? room, begin_datetime, end_datetime
    room.check_date_is_enable(begin_datetime) && room.check_date_is_enable(end_datetime)
  end

  def to_int_if_not number
    number.is_a?(Integer) ? number : number.to_i
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<h2>房間列表</h2>
<% @rooms = [] %>
<!--
<table>
  <thead>
    <tr>
      <th>類型</th>
      <th>房間號碼</th>
      <th>價格</th>
      <th>預約狀態</th>
      <% if user_signed_in? %><th>歷史預約紀錄</th><% end %>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_type.room_type_zh %></td>
        <td><%= room.room_number %></td>
        <td><%= room.price %></td>
        <td>
        <% if user_signed_in? %>
          <%= room.reservation_number ? link_to('已預約', user_booking_record_path(current_user, room.reservation_number)) : link_to('預約', reservation_hotel_room_path(@hotel, room)) %>
        <% else %>
          <%= room.reservation_number ? '已額滿' : link_to('可預約', reservation_hotel_room_path(@hotel, room)) %>
        <% end %>
        </td>
        <% if user_signed_in? %>
          <td>
            <%= room.booking_records.count > 0 ? link_to('預約記錄', reservation_hotel_room_path(@hotel, room)) : '無紀錄' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
-->
<table>
  <thead>
    <tr>
      <th>房間類型</th>
      <th>房間價格</th>
      <th>容許人數</th>
    </tr>
  </thead>
  <tbody>
    <% @roomtyps.each do |room_type| %>
      <tr>
        <td><%= room_type.room_type_zh %></td>
        <td>200</td>
        <td>1</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/reservation.html.erb
<h2>預約 <%= @hotel.name %>: <%= @room.room_number %>房</h2>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<% if !@has_reservation %>
  <%= form_with url: booking_hotel_room_path do |form| %>
    <div class="field">
      <%= form.label :begin_datetime %>
      <%= form.date_field :begin_datetime %>
    </div>
    <div class="field">
      <%= form.label :end_datetime %>
      <%= form.date_field :end_datetime %>
    </div>
    <div class="field">
      <%= form.label :person_count, "入住人數" %>
      <%= form.number_field :person_count, value: 1 %>
    </div>
    <div class="field">
      <%= form.submit "預約" %>
    </div>
  <% end %>
<% end %>

<h2>過往預約記錄</h2>

<table>
  <thead>
    <tr>
      <th>預約時間</th>
      <th>預約狀態</th>
      <th>入住人數</th>
      <th>入住日</th>
      <th>退房日</th>
    </tr>
  </thead>

  <tbody>
    <% @room.booking_records.each do |record| %>
      <tr>
        <td><%= record.created_at.strftime("%F") %></td>
        <td><%= record.status %></td>
        <td><%= record.person_count %></td>
        <td><%= record.begin_date.strftime("%F") %></td>
        <td><%= record.end_date.strftime("%F") %></td>
      </tr>
    <% end %>
  </tbody>
</table>